name: Release

# Trigger ONLY on PR merge onto 'master' branch
on:
  pull_request:
    types: ['closed']
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com
      - name: Install Dependencies
        run: |
          npm ci
      - name: Version
        run: |
          npm run release
      - name: Commit
        run: |
          git push --follow-tags
      - name: Publish
          run: |
            npm publish --tag 'stable'
          env:
            NODE_AUTH_TOKEN: ${{secrets.npm_token}}
