# Checks and Automatically fixes Style and Formatting issues
#
# This action can be used to automatically fix code style and formatting issues
# in Pull Requests, rather than rejecting them outright. The downside to this
# approach is that to push further updates to the Pull Request will require you
# to first fetch and rebase, which can be a bit confusing if you don't know what
# is going on.
name: CI

# Trigger ONLY on Pull Requests targeting the 'master' or 'develop' branches.
on:
  pull_request:
    branches:
      - master

jobs:
  style:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        # Ensure the repo is cloned without a detached head!
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Setup
        run: |
          npm ci
      - name: Checking
        run: |
          npm run format
      - name: Fixing
        if: failure()
        # Fix the formatting issues, and then commit using the PR creators ID.
        run: |
          npm run format-fix
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com
          git commit -am "fix: code style"
          git push
