# Checks and automatically formats code files
name: Code Format and Style

# Trigger ONLY on Pull Requests targeting the 'develop' branch.
on:
    pull_request:
        branches:
            - develop

jobs:
    formatter:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
              # Ensure the repo is cloned without a detached head!
              with:
                  ref: ${{ github.event.pull_request.head.ref }}
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - name: Checking for formatting issues
              run: |
                  npm ci
                  npm run format
            - name: If required, repair and commit
              if: failure()
              run: |
                  npm run format-fix
                  git config --global user.name ${GITHUB_ACTOR}
                  git config --global user.email ${GITHUB_ACTOR}@users.noreply.github.com
                  git commit -am "fix: code formating issues"
                  git push
