# Automatically format files with Prettier
name: Checks and formats files using the configured formatter

# Trigger ONLY on Pull Requests targeting the 'develop' branch.
on:
  pull_request:
    branches:
      - develop

jobs:
  prettier:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        # Ensure the repo is cloned without a detached head!
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Checking for formatting issues
        run: |
          npm ci
          npm run format
      - name: If required, repair and commit
        if: failure()
        run: |
          npm run format-fix
          git config --global user.name 'Libero QC'
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git commit -am "fix: code formating issues"
          git push
